name: cointop
recipe: lamp
config:
  php: 8.2
  webroot: .

services:
  database:
    type: mysql
    creds:
      user: lamp
      password: lamp
      database: lamp

  phpmyadmin:
    type: phpmyadmin

events:
  post-start:
    - database: mysql -ulamp -plamp lamp < /app/database/schema.sql
