name: cointop
recipe: lamp
config:
  php: 8.2
  webroot: .
services:
  database:
    type: mysql
    creds:
      user: lamp
      password: lamp
      database: lamp
    config:
      files:
        - database/schema.sql
  phpmyadmin:
    type: phpmyadmin
