name: cointop
recipe: lamp
config:
  php: 8.2
  webroot: .
  database: mysql:8.0
  services:
    database:
      creds:
        user: lamp
        password: lamp
        database: lamp
      config:
        files:
          - database/schema.sql

services:
  phpmyadmin:
    type: phpmyadmin