CREATE TABLE IF NOT EXISTS cryptocurrencies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(20, 8) NOT NULL,
    percent_change_24h DECIMAL(10, 4) NOT NULL,
    market_cap BIGINT UNSIGNED NOT NULL,
    volume_24h BIGINT UNSIGNED NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);